/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    IconPark: typeof import('./src/components/common/iconPark.vue')['default']
    Menu: typeof import('./src/components/layout/menu/index.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/menuList.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/playerController.vue')['default']
    PlayerList: typeof import('./src/components/layout/footer/playerList.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/playerSong.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongItem: typeof import('./src/components/layout/page/songItem.vue')['default']
  }
}
